name: PreBooking Scheduler

# Run every 1 minute
on:
  schedule:
    - cron: '* * * * *'  # Every minute
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  execute-prebookings:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Max 5 minutes (safety)

    steps:
      - name: Execute PreBooking Scheduler
        run: |
          echo "🚀 Triggering PreBooking Scheduler..."

          RESPONSE=$(curl -X POST ${{ secrets.APP_URL }}/api/cron/prebooking-scheduler \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --max-time 300 \
            --silent \
            --show-error \
            --write-out "\nHTTP_CODE:%{http_code}")

          HTTP_CODE=$(echo "$RESPONSE" | grep "HTTP_CODE:" | cut -d: -f2)
          BODY=$(echo "$RESPONSE" | sed '/HTTP_CODE:/d')

          echo "📊 Response Code: $HTTP_CODE"
          echo "📄 Response Body: $BODY"

          if [ "$HTTP_CODE" != "200" ]; then
            echo "❌ Scheduler failed with HTTP $HTTP_CODE"
            exit 1
          fi

          echo "✅ Scheduler executed successfully"

      - name: Report Failure
        if: failure()
        run: |
          echo "❌ PreBooking Scheduler failed"
          echo "Check the logs above for details"