name: Refresh Aimharder Sessions

on:
  schedule:
    # Ejecutar cada 6 horas (a las 00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite ejecución manual

jobs:
  refresh-sessions:
    runs-on: ubuntu-latest

    steps:
    - name: Refresh Sessions
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.INTERNAL_API_KEY }}" \
          -d '{"batchSize": 20, "hoursThreshold": 6}' \
          ${{ secrets.APP_URL }}/api/internal/refresh-sessions

    - name: Log Result
      run: echo "Session refresh job completed at $(date)"